### ISSUE TITLE
关于官方模块中视频模块的请求

### ISSUE THREAD

**Issue by leeruibin** [baetyl/baetyl#112]
您好，请问能否提供一下官方本地视频接入模块的测试样例，目前在云端与本地进行测试，其他的模块都可以进行测试，如计算模块可以测试函数，local-hub可以通过MQTTBox进行测试，但视频接入模块却没找到相关的测试案例说明，不知道这个模块该如何进行测试，希望能够提供一下相关的说明，谢谢您！

**Comment by ludanfeng** [comment]
@leeruibin 目前openedge整个在重构，各个模块也都在调整，并且视频模块还没成熟，等正式推出后，我们会提供文档，谢谢关注

**Comment by ludanfeng** [comment]
代码已经开源，参考baetyl-video-infer模块

**Comment by jaffe-fly** [comment]
> 代码已经开源，参考baetyl-video-infer模块 使用和设计文档后续推出

这个在哪里，没找到
