### ISSUE TITLE
使用mosquitto镜像，实例无法启动

### ISSUE THREAD

**Issue by AngelaZhao** [baetyl/baetyl#178]
**Describe the bug**
按照example中的示例配置后，mosquitto实例无法启动，一直在启停
openedge.log的日志如下
![image](https://user-images.githubusercontent.com/6222260/55405813-700a8c80-558d-11e9-9b87-14a17e9af444.png)
mosquitto container日志如下
![image](https://user-images.githubusercontent.com/6222260/55406669-228f1f00-558f-11e9-838b-3aa273fa79a5.png)

**Comment by ludanfeng** [comment]
试试对应的宿主机目录加个可写权限
