### ISSUE TITLE
导入pytorch包后，函数实例无法启动，一直重启

### ISSUE THREAD

**Issue by sycdxf** [baetyl/baetyl#210]
**Describe the bug**
在正常配置函数配置文件的情况下，若在python程序中导入pytorch的torch包，则函数实例无法启动成功，一直重启直至超时停止；若不做导入操作，只写简单的处理程序，则函数实例启动正常。
程序在自己通过dockerfile文件构建的python镜像启动的容器中导入相关包能够正常运行。

**Comment by chensheng0** [comment]
@sycdxf 可以把你说的这几种情况的代码发下吗？

**Comment by chensheng0** [comment]
给下版本信息，启动模式。

**Comment by sycdxf** [comment]
昨晚未看到邮件，抱歉，今天会把相关代码打包发送


 
---原始邮件---
发件人: "chensheng"<notifications@github.com>
发送时间: 2019年4月22日 19:37:04
收件人: "baidu/openedge"<openedge@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"sycdxf"<1350661935@qq.com>;
主题: Re: [baidu/openedge] 导入pytorch包后，函数实例无法启动，一直重启 (#210)



给下版本信息，启动模式。

**Comment by sycdxf** [comment]
### 使用的是0.1.2版的镜像，以docker模式启动；配置文件参照示例配置进行
### 代码包内容如下
![image](https://user-images.githubusercontent.com/14997764/56549656-f70fbb00-65b5-11e9-9492-7d89b1c4be21.png)
### 在宿主机上运行的代码tein.py如下,能够正常输出结果
![image](https://user-images.githubusercontent.com/14997764/56549751-376f3900-65b6-11e9-8b6e-d8a4c172a9a4.png)
### 在容器中运行的代码index.py如下，一直重启
![image](https://user-images.githubusercontent.com/14997764/56549884-a0ef4780-65b6-11e9-8a9e-3337a0a1a6c3.png)
### 对比测试的代码index1.py如下，一直重启
![2](https://user-images.githubusercontent.com/14997764/56550487-5373da00-65b8-11e9-8379-96e692d243dd.png)
### 对比测试代码index2.py如下，正常运行
![1](https://user-images.githubusercontent.com/14997764/56550372-0b54b780-65b8-11e9-940e-0e8786cf4676.png)

**Comment by chensheng0** [comment]
先前的镜像基于 Apline， Alpine 用的是 musl libs, Pytorch 底层调用的是 glibc，所以会出错。目前已经修复这个bug。也可以参考这篇文章 https://github.com/baidu/openedge/blob/master/doc/zh-cn/customize/How-to-import-third-party-libraries-for-python-runtime.md
