### ISSUE TITLE
主程序 stop 后删除，Agent 模块镜像会频繁重启下发配置文件

### ISSUE THREAD

**Issue by kuailehaibin** [baetyl/baetyl#214]
**Describe the bug**
主程序 stop 后删除，Agent 模块镜像会频繁重启下发配置文件。
![image](https://user-images.githubusercontent.com/8502587/56502034-96e03100-6543-11e9-9e4b-00f8c176856d.png)

**To Reproduce**
1. sudo openedge stop
2. cd /usr/local && rm -rf bin/openedge etc var

然后 Agent 模块会频繁重启，重新下发配置文件，无法清除。

**Comment by ludanfeng** [comment]
fixed
