### ISSUE TITLE
More build, test and release scripts and documents

### ISSUE THREAD

**Issue by ludanfeng** [baetyl/baetyl#24]
More build, test and release scripts and documents

**Comment by Teeina** [comment]
Hi, Do you have any detailed descriptions or documents in English?

**Comment by Teeina** [comment]
Thanks @kuailehaibin. Now i can find more through the readme and the website you provided. And i've got some questions here. 
I noticed that in the introduction you mentioned that it is the Cloud Management Suite which helps to manage the configuration of OpenEdge to perform process such as upgrading, and the most preferable cloud management suite is BIE. Then, could OpenEdge run on its own, like without the help from other Baidu Products such as BIE or IoT Hub? Or can we use other open source services to substitute these products?
Next, is OpenEdge communicating with both the IoT device and remote data consumer(e.g. cloud) through the iothub in your graph?
Thanks.
Teeina

**Comment by kuailehaibin** [comment]
@Teeina Many thanks for your attention. Yeah, BIE(include Cloud Management Suite) is designed for managing OpenEdge configuration better, also include OpenEdge upgrade, etc. Comparing with BIE, OpenEdge is an open source framework, which provide hub, function, remote modules, and is designed for developers. Once you have enough understanding of OpenEdge design and using, you can write the module configuration by youself(no need through BIE cloud management suit).

For the first question, OpenEdge has been connected to other Baidu products, such as IoT Hub, Rule Engine, TSDB, Visualization, BOS(Baidu Object Storage), etc. Also, you can develop your own module, more details refer to:

> + [how-to-develop-a-customize-runtime-for-OpenEdge](https://github.com/baidu/openedge/blob/master/doc/us-en/customize/How-to-develop-a-customize-runtime-for-function.md)
> + [how-to-develop-a-customize-module-for-OpenEdge](https://github.com/baidu/openedge/blob/master/doc/us-en/customize/How-to-develop-a-customize-module-for-openedge.md)

Second question,  remote module is designed to communicating with remote service, not only iothub. We will provide some practice documents, such as `OpenEdge-communicate-with-awshub-through-remote-module`. 

And we will provide all documents in English about one week later([https://openedge.tech](https://openedge.tech)). Please pay more attention.

Besides, the agent module connected to the cloud(Cloud Management Suite) in the next version will be independent. For developers, they can develop their own agent module for other platforms. The OpenEdge itself can also run offline independently, without the need for a cloud.

Thanks
kuailehaibin
