### ISSUE TITLE
Makefile:24: recipe for target 'baetyl' failed

### ISSUE THREAD

**Issue by hongbosen** [baetyl/baetyl#465]
**Describe the bug**
Makefile:24: recipe for target 'baetyl' failed

**OS-platform (please complete the following information):**
 - OS: Ubuntu18
 - CPU: arm64
 - Baetyl Version  0.1.6

**Additional context**
BUILD baetyl
CGO_ENABLED=1 CC=cc go build -ldflags "-X 'github.com/baetyl/baetyl.Revision=git-2e9eeb8' -X 'github.com/baetyl/baetyl.Version=git-2e9eeb8' -X 'github.com/baetyl/baetyl.DefaultPrefix=/usr/local' -X 'github.com/baetyl/baetyl.DefaultConfigPath=etc/baetyl/baetyl.yml' -X 'github.com/baetyl/baetyl.DefaultLoggerPath=var/log/baetyl.log' -X 'github.com/baetyl/baetyl.DefaultDataPath=var/lib/baetyl' -X 'github.com/baetyl/baetyl.DefaultPidPath=var/run/baetyl.pid' -X 'github.com/baetyl/baetyl.DefaultAPIAddress=var/run/baetyl.sock'" -o baetyl ./cmd/baetyl
# github.com/baetyl/baetyl/schema/v3
schema/v3/appconfig.go:335:48: syntax error: unexpected { at end of statement
schema/v3/appconfig.go:345:56: syntax error: unexpected { at end of statement
schema/v3/appconfig.go:350:46: syntax error: unexpected func, expecting comma or )
schema/v3/appconfig.go:355:2: syntax error: non-declaration statement outside function body
# github.com/baetyl/baetyl/protocol/mqtt
protocol/mqtt/dialer.go:6:2: imported and not used: "time"
protocol/mqtt/dialer.go:31:42: not enough arguments in call to transport.NewDialer
	have ()
	want (transport.DialConfig)
protocol/mqtt/dialer.go:32:3: d.TLSConfig undefined (type *Dialer has no field or method TLSConfig)
Makefile:24: recipe for target 'baetyl' failed
make: *** [baetyl] Error 2

**Comment by hongbosen** [comment]
Anyone help me?

**Comment by ludanfeng** [comment]
本地启用了go mod了吗？
