### ISSUE TITLE
新手教程

### ISSUE THREAD

**Issue by authorfu** [baetyl/baetyl#577]
有没有什么新手教程啊，我看readme都是介绍。比如怎么搭建，怎么运行，我看一个文档都没有。

**Comment by zxxf18** [comment]
hi，这里有中文版的文档 https://docs.baetyl.io/zh_CN/latest/

**Comment by authorfu** [comment]
有关于function的，python的函数配置么？还是没找到。你们demo的界面有。趴代码到grpc的80端口，然后就没了

**Comment by hannatao** [comment]
openapi中已更新相关内容
