### ISSUE TITLE
Hi3559A native mode error

### ISSUE THREAD

**Issue by leeyoung48** [baetyl/baetyl#64]
wanna try to run on Hi3559A dev board, some errors ocurred when starting openedge, do I miss some configs?  

~ # openedge
DEBU[1970-01-01T01:44:01Z] work dir: /usr/local                          openedge=master
INFO[1970-01-01T01:44:01Z] entry (map[bin/openedge-hub:{} bin/openedge-function:{}]) prepared  mode=native openedge=master
DEBU[1970-01-01T01:44:01Z] bin/openedge-hub [localhub -c /usr/local/var/db/openedge/module/localhub/module.yml]  mode=native openedge=master
INFO[1970-01-01T01:44:01Z] resident module (localhub) started            mode=native openedge=master
DEBU[1970-01-01T01:44:01Z] bin/openedge-function [localfunc -c /usr/local/var/db/openedge/module/localfunc/module.yml]  mode=native openedge=master
INFO[1970-01-01T01:44:01Z] resident module (localfunc) started           mode=native openedge=master
INFO[1970-01-01T01:44:01Z] all resident modules started                  mode=native openedge=master
DEBU[1970-01-01T01:44:01Z] module starting                               module=localfunc
DEBU[1970-01-01T01:44:01Z] next reconnect                                dispatcher=mqtt module=localfunc
ERRO[1970-01-01T01:44:01Z] failed to create new client                   dispatcher=mqtt error="dial tcp :1883: connect: invalid argument" module=localfunc
DEBU[1970-01-01T01:44:01Z] delay reconnect: 500ms                        dispatcher=mqtt module=localfunc
DEBU[1970-01-01T01:44:01Z] task of routing message (Q0) begins           component=sink module=localhub sink="$rule/msgqos0"
DEBU[1970-01-01T01:44:01Z] task of processing message from channel (Q1) begins  component=rule module=localhub target="$rule/topic"
DEBU[1970-01-01T01:44:01Z] task of processing message from channel (Q1) begins  component=rule module=localhub target="$rule/msgqos0"
DEBU[1970-01-01T01:44:01Z] task of waiting acknowledge begins            component=rule module=localhub target="$rule/msgqos0"
DEBU[1970-01-01T01:44:01Z] task of processing message from channel (Q0) begins  component=rule module=localhub target="$rule/msgqos0"
DEBU[1970-01-01T01:44:01Z] task of waiting acknowledge begins            component=rule module=localhub target="$rule/topic"
DEBU[1970-01-01T01:44:01Z] task of routing message (Q1) begins with offset=1  component=sink module=localhub sink="$rule/topic"
DEBU[1970-01-01T01:44:01Z] task of processing message from channel (Q0) begins  component=rule module=localhub target="$rule/topic"
DEBU[1970-01-01T01:44:01Z] 1 offset(s) persisted: map[$rule/topic:0]     component=broker module=localhub
DEBU[1970-01-01T01:44:01Z] next reconnect                                dispatcher=mqtt module=localfunc
ERRO[1970-01-01T01:44:01Z] failed to create new client                   dispatcher=mqtt error="dial tcp :1883: connect: invalid argument" module=localfunc
DEBU[1970-01-01T01:44:01Z] delay reconnect: 1s                           dispatcher=mqtt module=localfunc
DEBU[1970-01-01T01:44:02Z] next reconnect                                dispatcher=mqtt module=localfunc
ERRO[1970-01-01T01:44:02Z] failed to create new client                   dispatcher=mqtt error="dial tcp :1883: connect: invalid argument" module=localfunc
DEBU[1970-01-01T01:44:02Z] delay reconnect: 2s                           dispatcher=mqtt module=localfunc
DEBU[1970-01-01T01:44:04Z] next reconnect                                dispatcher=mqtt module=localfunc
ERRO[1970-01-01T01:44:04Z] failed to create new client                   dispatcher=mqtt error="dial tcp :1883: connect: invalid argument" module=localfunc
DEBU[1970-01-01T01:44:04Z] delay reconnect: 4s                           dispatcher=mqtt module=localfunc
DEBU[1970-01-01T01:44:08Z] next reconnect                                dispatcher=mqtt module=localfunc
ERRO[1970-01-01T01:44:08Z] failed to create new client                   dispatcher=mqtt error="dial tcp :1883: connect: invalid argument" module=localfunc
DEBU[1970-01-01T01:44:08Z] delay reconnect: 8s                           dispatcher=mqtt module=localfunc
DEBU[1970-01-01T01:44:16Z] next reconnect                                dispatcher=mqtt module=localfunc
ERRO[1970-01-01T01:44:16Z] failed to create new client                   dispatcher=mqtt error="dial tcp :1883: connect: invalid argument" module=localfunc
DEBU[1970-01-01T01:44:16Z] delay reconnect: 16s                          dispatcher=mqtt module=localfunc
DEBU[1970-01-01T01:44:32Z] next reconnect                                dispatcher=mqtt module=localfunc
ERRO[1970-01-01T01:44:32Z] failed to create new client                   dispatcher=mqtt error="dial tcp :1883: connect: invalid argument" module=localfunc

**Comment by ludanfeng** [comment]
@leeyoung48 初步判断是你的设备支持IPv6，把配置里的:1883改成0.0.0.0:1883或者127.0.0.1：1883试试，有问题再反馈，多谢。IPv6适配工作我们还没开展，以后安排。

**Comment by leeyoung48** [comment]
修改了localfunc的yml，还是一样的错误
~ # cat /usr/local/var/db/openedge/module/localfunc/module.yml
name: localfunc
hub:
  address: tcp://0.0.0.0:1883
  username: test
  password: hahaha
rules:
  - id: rule-e1iluuac1
    subscribe:
      topic: t
      qos: 1
    compute:
      function: sayhi
    publish:
      topic: t/hi
      qos: 1
functions:
  - id: func-nyeosbbch
    name: 'sayhi'
    runtime: 'python27'
    handler: 'sayhi.handler'
    codedir: 'var/db/openedge/module/func-nyeosbbch'
    entry: "bin/openedge_function_runtime_python27.py"
    env:
      USER_ID: acuiot
    instance:
      min: 0
      max: 100
      timeout: 30s
logger:
  path: var/log/openedge/localfunc/localfunc.log
  console: true
  level: "debug"
~ # cat /usr/local/var/db/openedge/module/localhub/module.yml
name: localhub
listen:
  - tcp://0.0.0.0:1883
principals:
  - username: 'test'
    password: 'be178c0543eb17f5f3043021c9e5fcf30285e557a4fc309cce97ff9ca6182912'
    permissions:
      - action: 'pub'
        permit: ['#']
      - action: 'sub'
        permit: ['#']
subscriptions:
  - source:
      topic: 't'
    target:
      topic: 't/topic'
logger:
  path: var/log/openedge/localhub/localhub.log
  console: true
  level: "debug"
~ #

**Comment by ludanfeng** [comment]
@leeyoung48  你是源码编译安装的吗？我们没有海思的板子，一时调试不了，如果能拿到板子我们调试看看。

**Comment by xwdreamer** [comment]
@leeyoung48 
给一下开发部的参数信息，哪里买的海思开发板，能否给个淘宝或者官方商城的链接。
