### ISSUE TITLE
GPU share的支持如何使用

### ISSUE THREAD

**Issue by yaqisheng** [baetyl/baetyl#657]
在文档中，我看到了GPU共享的支持，说是完成了接口的定义，需要提供GPU share的模块，不知所谓的模块该如何找？是vGPU或者vComputeServer或者Bitfusion ？可以聊一聊么？

**Comment by hannatao** [comment]
gpu共享我们当前尝试接入的vGPU，需要用户自行在边缘设备进行nvidia docker以及vGPU的安装。对于baetyl来说，主要是开放resource limits以及requests的配置，使得用户可以对baetyl下发的应用进行算力和显存的限制。
