### ISSUE TITLE
关于baetyl 2.2 支持Edgex Foundry 的疑问

### ISSUE THREAD

**Issue by hongcaohu** [baetyl/baetyl#658]
请问在哪里体现了对Edgex Foundry的支持呢，或者有相关文档么？

**Comment by lileding** [comment]
现在你可以通过baetyl-cloud从远程向baetyl实例部署一个EdgeX服务，后者是按照k8s服务的形式运行，这样可以提高edgex服务的交付效率和可管理性。
关于2.2的文档我们还在更新当中，未来几周内会提供相关的部署手册。

**Comment by hongcaohu** [comment]
@lileding 多谢了，Edgex服务是可以在一个Service配置中下发么，还是Edgex中所有的服务都要以Service的形式一个一个的配置？期待新版本的openapi和手册

**Comment by hongcaohu** [comment]
@lileding 多谢了，Edgex服务是可以在一个Service配置中下发么，还是Edgex中所有的服务都要以Service的形式一个一个的配置？期待新版本的openapi和手册
