### ISSUE TITLE
baetyl应用使用私用镜像仓库凭证的问题

### ISSUE THREAD

**Issue by benjaminlinken** [baetyl/baetyl#661]
在baetyl-cloud使用api创建了一个appliation和一个registry，并配置application使用该registry，部署到边端，在边端kubectl describe该application对应的deployment后发现并没有ImagePullSecrets字段，按照代码逻辑应该是要有的吧？

**Comment by hannatao** [comment]
我这边按照你的叙述尝试了一遍，边缘节点的应用是有配置的ImagePullSecrets字段的
<img width="495" alt="195ec280d4c8a7a9a784f57d9c3b3184" src="https://user-images.githubusercontent.com/20313556/124854206-9c69aa80-dfd9-11eb-9bdc-053f733ce0ec.png">
