### ISSUE TITLE
关于gpu监控功能

### ISSUE THREAD

**Issue by benjaminlinken** [baetyl/baetyl#666]
您好，目前阅读代码发现gpu监控相关功能需通过BaetylGPUStatsExtension函数获取，但是源码中并没有相关的实现，这部分是需要自行实现吗？后续是否开源？
![image](https://user-images.githubusercontent.com/12994074/134772434-19b4df0e-f475-4fd2-8467-821fab6a9f1e.png)

**Comment by hannatao** [comment]
暂时开源版本未实现，且未有开源计划，需要自行实现该函数。
