### ISSUE TITLE
baetyl 开源版本和企业版本有什么区别？只是开源版本没有dashboard 其它都是提供了？需要自己实现dashboard?

### ISSUE THREAD

**Issue by liushoubing** [baetyl/baetyl#701]
baetyl 开源版本和企业版本有什么区别？只是开源版本没有dashboard 其它都是提供了？需要自己实现dashboard?

**Comment by hannatao** [comment]
除了dashboard之外，还会有远程调试，设备管理，节点预配等附加功能。但是最核心的端云同步逻辑，还是在开源版本。
