### ISSUE TITLE
add Certificate Auth python demo code

### ISSUE THREAD

**Issue by xwdreamer** [baetyl/baetyl#87]
In this page:https://cloud.baidu.com/doc/BIE/BIEdownload.html#.E4.B8.8B.E8.BD.BDMQTT.fx.E5.AE.A2.E6.88.B7.E7.AB.AF

I download  Python demo code.
I found this demo code doesn't support Certificate Auth. Only support Secret base Auth.
Suggestion:
1.  give secret based Auth demo code.(done)
2. give certificate based Auth demo code.(need to add)

**Comment by kuailehaibin** [comment]
@xwdreamer Many thanks! We will provide more demo code due to multiple connection methods of localhub(such as username/password, ssl/tls, websocket, etc).
