### ISSUE TITLE
本地与云端连接测试时出现消息循环

### ISSUE THREAD

**Issue by leeruibin** [baetyl/baetyl#93]
**Describe the bug**
在测试云端与本地连接的阶段已经成功连通云端与本地的连接，测试时通过MQTTBox连接本地local-hub使用MQTT.fx连接天工云，本地只运行两个模块local-hub和remote模块，remote模块连接天工云并订阅远程的 't' 主题，连接本地local-hub订阅 'topic' 主题，测试阶段使用MQTTBox发送消息到云端MQTT.fx可以正常接收，但使用MQTT.fx发送 't' 主题消息时，本地接收的消息一直循环，使用天工云网站的测试连接发送消息也是同样的结果。
配置与循环界面截图如下
remote配置
![screenshot from 2019-01-24 14-06-20](https://user-images.githubusercontent.com/26408630/51660368-7a863400-1fe8-11e9-8c3f-0db75d2dc06f.png)
local-hub配置
![screenshot from 2019-01-24 14-07-56](https://user-images.githubusercontent.com/26408630/51660402-92f64e80-1fe8-11e9-97fe-6d2edd3799da.png)
消息循环
![screenshot from 2019-01-24 11-24-14](https://user-images.githubusercontent.com/26408630/51660436-b6b99480-1fe8-11e9-8a35-11ef80a50253.png)
使用天工云测试也出现循环
![screenshot from 2019-01-24 14-13-01](https://user-images.githubusercontent.com/26408630/51660451-c802a100-1fe8-11e9-988c-635a274bd93e.png)

**Comment by ludanfeng** [comment]
使用不当
后续增加简单检查配置死循环逻辑

**Comment by OlympusHo** [comment]
> 使用不当
> 后续增加简单检查配置死循环逻辑

你好，我也出现了同样问题：消息一直在循环。怀疑是remote-mqtt模块内部成环了。
请问该问题解决了没？

**Comment by ludanfeng** [comment]
@OlympusHo 向hub订阅的主题和向remote订阅的整体不要现成包含关系。

为了提供沟通效率，推荐加入微信社区群，可以让[BAETYL小助手](https://baetyl.bj.bcebos.com/Wechat/Wechat-Baetyl.png)拉你进群。

**Comment by liangyuanpeng** [comment]
这确实是用户使用上的问题，但是很有可能根本没有意识到自己错误了使用了循环订阅，因此我认为baetyl还是很需要做一个检查防止这种情况的出现

> @OlympusHo 向hub订阅的主题和向remote订阅的主题不要形成包含关系。
> 
> 为了提供沟通效率，推荐加入微信社区群，可以让[BAETYL小助手](https://baetyl.bj.bcebos.com/Wechat/Wechat-Baetyl.png)拉你进群。
